<a href="https://colab.research.google.com/github/minseokey/Data_Science/blob/main/DataScience_04_1_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
y = torch.FloatTensor([[1,2,3], [4,5,6], [7,8,9]])
print("x =", x)
print("y =", y)

print("Size:", x.size())
print("Shape:", x.shape)
print("차원(랭크):", x.ndimension())

x0 = torch.unsqueeze(x, 0)
x1 = torch.unsqueeze(x, 1)
x2 = torch.unsqueeze(x, 2)
print("x0.shape:", x0.shape)
print("x1.shape:", x1.shape)
print("x2.shape:", x2.shape)
print("x0 =", x0)
print("x1 =", x1)
print("x2 =", x2)

x3 = torch.squeeze(torch.squeeze(x0))
print("x3 =", x3)
print("x3.shape =", x3.shape)

x4 = x.view(9)
x5 = x.view(1,3,3)
print("x4 =", x4)
print("x5 =", x5)


x = tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
y = tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
Size: torch.Size([3, 3])
Shape: torch.Size([3, 3])
차원(랭크): 2
x0.shape: torch.Size([1, 3, 3])
x1.shape: torch.Size([3, 1, 3])
x2.shape: torch.Size([3, 3, 1])
x0 = tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
x1 = tensor([[[1, 2, 3]],

        [[4, 5, 6]],

        [[7, 8, 9]]])
x2 = tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]])
x3 = tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
x3.shape = torch.Size([3, 3])
x4 = tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
x5 = tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [ ]:
import torch
x = torch.FloatTensor([[1,2],[3,4],[5,6]])
w = torch.randn(1,2,dtype=torch.float)
b = torch.randn(3,1,dtype=torch.float)
print(w)
print(b)
result = torch.mm(x,torch.t(w)) +b  #xw +b
print(result)

tensor([[ 1.2038, -0.4189]])
tensor([[ 0.0914],
        [-0.4350],
        [-1.1770]])
tensor([[0.4573],
        [1.5007],
        [2.3285]])


In [ ]:
import torch
w = torch.tensor(5.0 ,requires_grad = True)
l = (w**3 * 3) +(4*w) + 7
l.backward()
print(w.grad)

tensor(229.)


In [ ]:
import torch
x_train = torch.FloatTensor([[1,2], [3,2], [3,7], [1,1], [1,0]])
y_train = torch.FloatTensor([[4], [8], [23], [1], [-2]])

lr = 0.001

w = torch.randn(2,1)
b = torch.randn(1)

for epoch in range(10000):

  w.requires_grad_(True)
  b.requires_grad_(True)

  h = torch.mm(x_train,w)+b
  cost = torch.mean((y_train-h) **2)     # 가설과 현재값의 차이

  cost.backward()
  with torch.no_grad():
    w = w - lr* w.grad     #update
    b = b - lr* b.grad

    if epoch % 100 == 0:
      print( 'epoch: {}, cost: {:.6f}, W: {}, b: {}'.format(epoch, 
      cost.item(), w.squeeze(), b))





epoch: 0, cost: 201.696182, W: tensor([-1.1326,  0.0820]), b: tensor([-1.3396])
epoch: 100, cost: 2.628255, W: tensor([0.4496, 2.9603]), b: tensor([-0.8306])
epoch: 200, cost: 2.056056, W: tensor([0.5121, 3.1166]), b: tensor([-0.9441])
epoch: 300, cost: 1.878457, W: tensor([0.5202, 3.1493]), b: tensor([-1.0728])
epoch: 400, cost: 1.728564, W: tensor([0.5338, 3.1700]), b: tensor([-1.1925])
epoch: 500, cost: 1.598504, W: tensor([0.5536, 3.1849]), b: tensor([-1.3037])
epoch: 600, cost: 1.483428, W: tensor([0.5782, 3.1954]), b: tensor([-1.4076])
epoch: 700, cost: 1.380055, W: tensor([0.6064, 3.2023]), b: tensor([-1.5049])
epoch: 800, cost: 1.286124, W: tensor([0.6372, 3.2064]), b: tensor([-1.5967])
epoch: 900, cost: 1.200049, W: tensor([0.6699, 3.2083]), b: tensor([-1.6834])
epoch: 1000, cost: 1.120689, W: tensor([0.7038, 3.2085]), b: tensor([-1.7658])
epoch: 1100, cost: 1.047198, W: tensor([0.7384, 3.2073]), b: tensor([-1.8441])
epoch: 1200, cost: 0.978931, W: tensor([0.7734, 3.2050]), b:

In [ ]:
x = torch.tensor([[5,10]],dtype=torch.float)
t = torch.mm(x,w) +b
print(t.item())

35.89519119262695


In [ ]:
from sklearn.linear_model import LinearRegression
x = [[1,2], [3,2], [3,7], [1,1], [1,0]]
y = [[4], [8], [23], [1], [-2]]

lr = LinearRegression()
lr.fit(x,y)
print(lr.coef_,lr.intercept_) #coef = w, intercept = b
print(lr.predict([[5,10]]))

[[2. 3.]] [-4.]
[[36.]]
