<a href="https://colab.research.google.com/github/minseokey/Data_Science/blob/main/Data_Science_06_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
x_train = torch.FloatTensor([ [1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5],
 [1,2,5,6], [1,6,6,6], [1,7,7,7] ])
y_train = torch.FloatTensor([ [0,0,1], [0,0,1], [0,0,1], [0,1,0], [0,1,0], [0,1,0],
 [1,0,0], [1,0,0] ])
W = torch.zeros(4, 3, requires_grad=True) # 4는 x의 입력차수 ,3은 class개수
b = torch.zeros(1, 3, requires_grad=True) # b는 class 별로 하나씩 그려지는 가설함수의 상수값 

optim = torch.optim.Adam([W,b],lr = 0.1)

for epoch in range(3001):
  #가설값 계산, cost계산, 
  h = torch.softmax(torch.mm(x_train,W) + b, dim = 1)
  #dim은 softmax정규화중에 어느차원 까지를 정규화 할지. 0 => 메트릭스 세로 한줄의 합 1, 1 => 메트릭스 가로 한 줄의 합 1
  cost = torch.mean(torch.sum(-torch.log(h)*y_train,dim = 1)) # CrossEntropy
  #cost = (-torch.log(h)*y_train).sum(dim = 1).mean()
  optim.zero_grad() # 기울기 0으로 초기화
  cost.backward() # cost기준 편미분
  optim.step()
  with torch.no_grad():
    print(f"epoch:{epoch}, cost:{cost.item()}")


epoch:0, cost:1.0986123085021973
epoch:1, cost:1.0999528169631958
epoch:2, cost:1.1307729482650757
epoch:3, cost:0.8231020569801331
epoch:4, cost:0.8229138851165771
epoch:5, cost:0.8615760803222656
epoch:6, cost:0.8082639575004578
epoch:7, cost:0.7189830541610718
epoch:8, cost:0.6710287928581238
epoch:9, cost:0.6637334227561951
epoch:10, cost:0.679209291934967
epoch:11, cost:0.6795008778572083
epoch:12, cost:0.6470802426338196
epoch:13, cost:0.6056264638900757
epoch:14, cost:0.5827548503875732
epoch:15, cost:0.5772790908813477
epoch:16, cost:0.5769322514533997
epoch:17, cost:0.5774424076080322
epoch:18, cost:0.5688809156417847
epoch:19, cost:0.5463800430297852
epoch:20, cost:0.5250086784362793
epoch:21, cost:0.5159306526184082
epoch:22, cost:0.5132191181182861
epoch:23, cost:0.5103185772895813
epoch:24, cost:0.5055168867111206
epoch:25, cost:0.4962597191333771
epoch:26, cost:0.4822639226913452
epoch:27, cost:0.4704012870788574
epoch:28, cost:0.46522897481918335
epoch:29, cost:0.4626605

In [ ]:
import torch
import torch.nn.functional as F
import torch.nn as nn
x_train = torch.FloatTensor([ [1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5],
 [1,2,5,6], [1,6,6,6], [1,7,7,7] ])
y_train = torch.LongTensor([2,2,2,1,1,1,0,0,])

model = nn.Linear(4,3) # input은 4차원, output은 3차원, w와b의 모양을 자동으로 만들어준다.
# W = torch.zeros(4, 3, requires_grad=True) # 4는 x의 입력차수 ,3은 class개수
# b = torch.zeros(1, 3, requires_grad=True) # b는 class 별로 하나씩 그려지는 가설함수의 상수값 

optim = torch.optim.Adam(model.parameters(),lr = 0.1)

for epoch in range(3001):
  #가설값 계산, cost계산, 
  
  h = model(x_train) + b
  #dim은 softmax정규화중에 어느차원 까지를 정규화 할지. 0 => 메트릭스 세로 한줄의 합 1, 1 => 메트릭스 가로 한 줄의 합 1
  
  cost = F.cross_entropy(h,y_train)
  #cost = (-torch.log(h)*y_train).sum(dim = 1).mean()
  #h 와 cost는 짝꿍, F.cross_entropy 에서는 두개를 묶어버림
  # F.cross_entropy => cost =  torch.mean(torch.sum(-torch.log(h.sofrmax(dim = 1))*y_train,dim = 1)), h는  torch.mm(x_train,W) + b
  # 또 원핫이 아닌 그냥 숫자로 넣어줘도 가능하다.


  optim.zero_grad() # 기울기 0으로 초기화
  cost.backward() # cost기준 편미분
  optim.step()
  with torch.no_grad():
    print(f"epoch:{epoch}, cost:{cost.item()}")


epoch:0, cost:23.395401000976562
epoch:1, cost:21.070402145385742
epoch:2, cost:18.745403289794922
epoch:3, cost:16.42040252685547
epoch:4, cost:14.095409393310547
epoch:5, cost:11.770800590515137
epoch:6, cost:9.475175857543945
epoch:7, cost:7.630530834197998
epoch:8, cost:6.674452781677246
epoch:9, cost:6.262969017028809
epoch:10, cost:5.940474033355713
epoch:11, cost:5.571205139160156
epoch:12, cost:5.125279903411865
epoch:13, cost:4.587336540222168
epoch:14, cost:3.9566497802734375
epoch:15, cost:3.242156982421875
epoch:16, cost:2.455357551574707
epoch:17, cost:1.6095004081726074
epoch:18, cost:0.7727314233779907
epoch:19, cost:0.30730918049812317
epoch:20, cost:0.38732799887657166
epoch:21, cost:0.6630045175552368
epoch:22, cost:0.9620776772499084
epoch:23, cost:1.2804110050201416
epoch:24, cost:1.5497968196868896
epoch:25, cost:1.7007087469100952
epoch:26, cost:1.7172372341156006
epoch:27, cost:1.6169757843017578
epoch:28, cost:1.4365909099578857
epoch:29, cost:1.2237180471420288

In [ ]:
x_test = torch.tensor([[1,11,10,9],[1,3,4,3],[1,1,0,1]],dtype = torch.float)
h = (model(x_test) + b).softmax(dim = 1)
print(h)
# [1,2,5,6,9,8,2]
# 그냥 max = 9 argmax = 9 의 인덱스 => 4
print(torch.argmax(h,dim = 1)) 

tensor([[1.0000e+00, 2.2446e-17, 2.1485e-35],
        [8.0017e-08, 3.6260e-01, 6.3740e-01],
        [4.5901e-31, 1.8394e-10, 1.0000e+00]], grad_fn=<SoftmaxBackward0>)
tensor([0, 2, 2])


In [ ]:
import numpy as np
from sklearn.linear_model import LogisticRegression
x_train = np.array([ [1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5],
 [1,2,5,6], [1,6,6,6], [1,7,7,7] ])
# y에 0, 1, 2 등 둘 이상의 class가 존재 => softmax regression
y_train = np.array([ 2, 2, 2, 1, 1, 1, 0, 0 ])
logistic = LogisticRegression() # 모델 생성
logistic.fit(x_train, y_train) # 학습
pred = logistic.predict([[1,11,10,9], [1,3,4,3], [1,1,0,1]]) 
print(pred) 


[0 2 2]
